[icons]
icons = "awesome6"
[theme]
theme = "solarized-dark"

#[[block]]
#block = "keyboard_layout"
#driver = "localebus"
## on_click = "xkb-switch -n"
#interval = 5

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
# interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:50,rot_interval:0.5)} "

[[block]]
block = "disk_space"
alert = 10.0
warning = 50.0

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:M)/$mem_total.eng(prefix:M)"

[[block]]
block = "cpu"

[[block]]
block = "temperature"
format = " $icon "
format_alt = " $icon $average avg, $max max "

[[block]]
block = "load"
format = " {1m} "
interval = 1

[[block]]
block = "sound"
device_kind = "source" # show mic state

[[block]]
block = "sound"
max_vol = 100
headphones_indicator = true

[[block]]
block = "battery"

[[block]]
block = "backlight"
invert_icons = true

[[block]]
block = "time"
#format = "%a %d/%m %R"
interval = 60
